import './globals.css'
import { PT_Sans_Narrow } from 'next/font/google'

const narrow = PT_Sans_Narrow({weight : '400',  subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={narrow.className}>{children}</body>
    </html>
  )
}
